services:
  - type: web
    name: sweet-sunday-dashboard
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: SHOPIFY_SHOP_DOMAIN
        sync: false
      - key: SHOPIFY_ADMIN_TOKEN
        sync: false
      - key: SHOPIFY_API_VERSION
        value: "2025-01"
